# Generated by Django 4.0.1 on 2022-03-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlink',
            name='label',
            field=models.CharField(choices=[('GITHUB', 'github'), ('LINKEDIN', 'linkedin')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Label',
        ),
    ]
