# Generated by Django 4.0.1 on 2022-03-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_alter_userlink_label_delete_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='level',
            field=models.CharField(choices=[('native speaker', 'NATIVE SPEAKER'), ('highly proficient', 'HIGHLY PROFICIENT')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Level',
        ),
    ]
