# Generated by Django 4.0.1 on 2022-03-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_alter_language_level_delete_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='level',
            field=models.CharField(choices=[('native speaker', 'NATIVE SPEAKER'), ('highly proficient', 'HIGHLY PROFICIENT'), ('very good command', 'VERY GOOD COMMAND')], max_length=50),
        ),
        migrations.AlterField(
            model_name='skills',
            name='skill_level',
            field=models.CharField(choices=[('novice', 'NOVICE'), ('begineer', 'BEGINEER'), ('skillfull', 'SKILLFULL'), ('experienced', 'EXPERIENCED'), ('expert', 'EXPERT')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userlink',
            name='label',
            field=models.CharField(choices=[('github', 'GITHUB'), ('linkedin', 'LINKEDIN')], max_length=50),
        ),
        migrations.DeleteModel(
            name='SkillLevel',
        ),
    ]
