# Generated by Django 4.0.1 on 2022-03-08 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resumes', '0004_alter_language_level_alter_skills_skill_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='status',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='skills',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skills',
            name='skill_level',
            field=models.CharField(choices=[('novice', 'NOVICE'), ('beginner', 'BEGINNER'), ('skillful', 'SKILLFUL'), ('experienced', 'EXPERIENCED'), ('expert', 'EXPERT')], max_length=50),
        ),
    ]
