# Generated by Django 4.0.1 on 2022-03-09 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_remove_skills_created_at_remove_skills_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='user',
        ),
    ]
